# Generated by Django 4.0.2 on 2022-05-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='watchlist',
            new_name='watchers',
        ),
    ]
